#!/bin/bash

if test -f package-lock.json
then
    rm package-lock.json
fi

if test -d node_modules
then
    rm -rf node_modules
fi

if ! npm i
then
    echo "Fail to run \"npm i\""
    exit 1
fi

git add . && git commit -m 'package-lock just generated by deploy.sh' && git push

if npm run build
then
    if git checkout master
    then
        shopt -s extglob
        if rm -rf -- !("."|".."|".git"|"deploy.sh"|"build")
        then
            shopt -u extglob
            mv build/* ./
            rmdir build
            git add .
            git commit -m 'Site atualizado usando update.sh'
            git push
            echo "https://josephseraos.github.io"
            git checkout source
        else
            shopt -u extglob
            echo "Fail to remove files"
            git checkout source
            exit 1
        fi
    else
        echo 'Attention!!! Something went wrong!!!'
        git checkout source
        exit 1
    fi
else
    echo "Fail to on building"
    exit 1
fi


